# Generated by Django 5.1.2 on 2024-10-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_user_user_type_formsubmission_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
